server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:memberdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create